# Generated by Django 2.2.1 on 2019-05-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190513_2021'),
        ('api', '0004_auto_20190514_0151'),
    ]

    operations = [
    ]
